spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: health_route
          uri: http://localhost:8080
          predicates:
            - Path=/bets/{segment}
        - id: login
          uri: http://localhost:8082
          predicates:
            - Path=/login
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
server:
  port: 8081