logging:
  level:
    org.springframework: trace
  structured:
    format:
      console: ecs
spring:
  application:
    name: API Gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: health_route
          uri: http://bet-service
          predicates:
            - Path=/bets/{segment}
        - id: login
          uri: http://login-service
          predicates:
            - Path=/login
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-server