logging:
  level:
    org.springframework: trace
  structured:
    format:
      console: ecs
spring:
  application:
    name: API Gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: health_route
          uri: http://bet-service
          predicates:
            - Path=/bets/{segment}
        - id: login
          uri: http://login-service
          predicates:
            - Path=/login
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-server
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  metrics:
    distribution:
      slo:
        spring.cloud.gateway.requests: PT0.1S,PT0.2S,PT0.5S,PT1.0S,PT5.0S,PT10.0S